name: smoltolk
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Adjust version as needed
  - numpy<2
  - pytorch
  - torchvision
  - torchaudio
  - datasets
  - transformers
  - wandb
  - pip
  - pip:
    - flash_attn
    - zerospeech-benchmarks[all]
